global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: /metrics

  - job_name: 'boot4-reference'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /actuator/prometheus
